### ISSUE TITLE
Netzob URL is no longer about Netzob

### ISSUE THREAD

**Issue by mhxion** [dloss/binary-parsing#15]
It seems the link to Netzob tool under [`Other Stand-alone Software`](https://github.com/dloss/binary-parsing#other-stand-alone-software) leads to the site `www.netzob.org`, the contents of which are no longer about what Netzob tool is about. Netzob's official GitHub [repository](https://github.com/netzob/netzob) has a [brief hint](https://github.com/netzob/netzob#helpfull-resources) to it that they actually refer to a [**archived version**](http://web.archive.org/web/20161227204116/http://www.netzob.org/) of their site which is what used to be the original homepage serving the actual Netzob, a reverse-engineering tool. To clarify:

| Netzob.org before (archived from 2016) ✅ | Netzob.org now ❌ |
|--------------------------|-----------------|
| <img width="384" alt="Screen Shot 2022-05-24 at 10 34 27 AM" src="https://user-images.githubusercontent.com/21981508/170075578-efa52d5b-e207-4a94-a8e2-93fc4aa18007.png"> | <img width="321" alt="Screen Shot 2022-05-24 at 10 34 52 AM" src="https://user-images.githubusercontent.com/21981508/170075805-8a8579fd-f5b2-4be2-811c-85ac27861acb.png"> |

I believe the domain `netzob.org` is still under their control, but the contents are totally irrelevant (something about _jobs_?) and no mention of Netzob as a reverse engineering tool, though I do not know why. I had to Google to get their actual repository.

For the purposes of this Awesome list, it'd be better if the link to Netzob referred to their GitHub repository: `github.com/netzob/netzob` instead `netzob.org` (until their site is fixed).

**Comment by dloss** [comment]
Fixed. Thank you!
