### ISSUE TITLE
Another declarative parser framework in Python

### ISSUE THREAD

**Issue by MatrixEditor** [dloss/binary-parsing#19]
Hi, I developed *another* binary parsing framework for Python. Is it possible to include it in the current framework list?

* [Here's](https://matrixeditor.github.io/caterpillar/reference/introduction.html#comparison) a small comparison across the listed Python frameworks targeting binary parsing.
* [Caterpillar](https://github.com/MatrixEditor/caterpillar): A Python 3.12+ library to pack and unpack structured binary data.

**Comment by dloss** [comment]
Added. Thank you for the suggestion and for developing the library!
